#!/usr/bin/env bash
#############################################################################
# Name:        scripts/build_appimage.sh
# Purpose:     Bundles Malama binary, icons, and desktop entry into AppImage
# Author:      Wanjare S. <samuelwanjare@protonmail.com>
# Created:     2026-08-11
# Copyright:   (c) 2026 Magpiny. All rights reserved.
# Licence:     GPL-3.0-or-later
#############################################################################

# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

# 1. Dynamically extract project version from CMakeLists.txt
VERSION=$(grep -oP 'project\(malama VERSION \K[0-9.]+' CMakeLists.txt || echo "0.2.9")
export VERSION

# 2. Configure update information header
export UPDATE_INFORMATION="gh-releases-zsync|magpiny|malama|latest|Malama-*-x86_64.AppImage.zsync"

echo "🔵 [ℹ️ INFO] => Building Malama AppImage v${VERSION}..."

# 3. Ensure linuxdeploy-x86_64.AppImage is present
if [ ! -f "linuxdeploy-x86_64.AppImage" ]; then
    echo "🔵 [ℹ️ INFO] => linuxdeploy tool not found in project root. Fetching tool..."
    if command -v curl &>/dev/null; then
        curl -sL "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -o linuxdeploy-x86_64.AppImage
    elif command -v wget &>/dev/null; then
        wget -q "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -O linuxdeploy-x86_64.AppImage
    else
        echo "❌ [ERROR] => Neither curl nor wget is available to download linuxdeploy."
        exit 1
    fi
    chmod +x linuxdeploy-x86_64.AppImage
fi

# 4. Perform release build
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j$(nproc)

# 5. Assemble AppDir structure
APP_DIR="AppDir"
rm -rf "${APP_DIR}"

mkdir -p "${APP_DIR}/usr/bin"
mkdir -p "${APP_DIR}/usr/share/applications"
mkdir -p "${APP_DIR}/usr/share/icons/hicolor/256x256/apps"
mkdir -p "${APP_DIR}/usr/share/metainfo"

# Convert icon to PNG format if only JPG exists
if [ -f "assets/malama.jpg" ] && [ ! -f "assets/malama.png" ]; then
    echo "🔵 [ℹ️ INFO] => Converting assets/malama.jpg to PNG format..."
    if command -v convert &>/dev/null; then
        convert assets/malama.jpg assets/malama.png
    else
        ffmpeg -y -i assets/malama.jpg assets/malama.png
    fi
fi

# Copy binary and CMake-configured desktop file into AppDir
cp build/malama "${APP_DIR}/usr/bin/malama"
cp build/malama.desktop "${APP_DIR}/usr/share/applications/malama.desktop"
cp assets/malama.png "${APP_DIR}/usr/share/icons/hicolor/256x256/apps/malama.png" 2>/dev/null || true

if [ -f "assets/org.magpiny.malama.metainfo.xml" ]; then
    cp assets/org.magpiny.malama.metainfo.xml "${APP_DIR}/usr/share/metainfo/"
fi

# Sanitize Exec entry inside AppDir desktop file
sed -i 's|^Exec=.*|Exec=malama %U|g' "${APP_DIR}/usr/share/applications/malama.desktop"

# 6. Execute linuxdeploy to assemble AppImage
./linuxdeploy-x86_64.AppImage \
    --appdir "${APP_DIR}" \
    --executable "${APP_DIR}/usr/bin/malama" \
    --desktop-file "${APP_DIR}/usr/share/applications/malama.desktop" \
    --icon-file "${APP_DIR}/usr/share/icons/hicolor/256x256/apps/malama.png" \
    --output appimage

# Handle desktop file naming case variations output by linuxdeploy
GENERATED_APPIMAGE=$(ls malama-*.AppImage Malama-*.AppImage 2>/dev/null | head -n 1)
if [ -n "${GENERATED_APPIMAGE}" ]; then
    mv "${GENERATED_APPIMAGE}" "Malama-v${VERSION}-x86_64.AppImage"
    echo "✅ [SUCCESS] => Generated Malama-v${VERSION}-x86_64.AppImage"
else
    echo "❌ [ERROR] => AppImage bundle was not generated by linuxdeploy."
    exit 1
fi
